=== mamund/grail-public/grail-demo-18-node-onboarding/schemas/observations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "GRAIL Observations",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "invocation",
      "response",
      "outputs",
      "result"
    ],
    "properties": {
      "invocation": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "affordance",
          "timestamp",
          "request"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "affordance": {
            "type": "string",
            "minLength": 1
          },
          "timestamp": {
            "type": "string",
            "format": "date-time"
          },
          "request": {
            "type": "object"
          }
        }
      },
      "response": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "status",
          "headers",
          "body"
        ],
        "properties": {
          "status": {
            "type": "integer",
            "minimum": 100,
            "maximum": 599
          },
          "headers": {
            "type": "object"
          },
          "body": {}
        }
      },
      "outputs": {
        "type": "object"
      },
      "result": {
        "type": "string",
        "enum": [
          "SUCCESS",
          "BLOCKED",
          "FAIL"
        ]
      }
    }
  }
}

=== mamund/grail-public/grail-demo-16-http-bindings-output/config/observations.json
[
  {
    "invocation": {
      "id": "inv-001",
      "affordance": "lookupCustomer",
      "timestamp": "2026-09-23T18:54:34.203Z",
      "request": {
        "method": "GET",
        "url": "http://localhost:3001/customers/customer-123",
        "headers": {},
        "body": null
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Wed, 23 Sep 2026 18:54:34 GMT",
        "etag": "\"customer-123-v1\"",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "id": "customer-123",
        "name": "Jordan",
        "account": {
          "id": "A97"
        }
      }
    },
    "outputs": {
      "accountId": "A97",
      "etag": "\"customer-123-v1\"",
      "httpStatus": 200
    },
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-002",
      "affordance": "lookupAccount",
      "timestamp": "2026-09-23T18:54:34.210Z",
      "request": {
        "method": "GET",
        "url": "http://localhost:3001/accounts/A97",
        "headers": {},
        "body": null
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Wed, 23 Sep 2026 18:54:34 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "id": "A97",
        "status": "active"
      }
    },
    "outputs": {},
    "result": "SUCCESS"
  }
]

=== mamund/grail-public/grail-demo-19-http-onboarding/config/observations.json
[
  {
    "invocation": {
      "id": "inv-001",
      "affordance": "startOnboarding",
      "timestamp": "2026-10-02T19:28:30.070Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/onboarding",
        "headers": {},
        "body": null
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "onboardingId": "ONB-7cc77b5c"
      }
    },
    "outputs": {
      "onboardingId": "ONB-7cc77b5c"
    },
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-002",
      "affordance": "createCustomerProfile",
      "timestamp": "2026-10-02T19:28:30.086Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/customers",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "onboardingId": "ONB-7cc77b5c",
          "name": "Jordan"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "customerId": "CUS-3d786679"
      }
    },
    "outputs": {
      "customerId": "CUS-3d786679"
    },
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-003",
      "affordance": "setCustomerAddress",
      "timestamp": "2026-10-02T19:28:30.091Z",
      "request": {
        "method": "PUT",
        "url": "http://localhost:3001/customers/CUS-3d786679/address",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "street": "100 Main Street",
          "city": "Cincinnati",
          "state": "OH",
          "postalCode": "45202"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "status": "SUCCESS"
      }
    },
    "outputs": {},
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-004",
      "affordance": "acceptTerms",
      "timestamp": "2026-10-02T19:28:30.109Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/customers/CUS-3d786679/terms",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "termsVersion": "2026-09"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "status": "SUCCESS"
      }
    },
    "outputs": {},
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-005",
      "affordance": "setCustomerDetails",
      "timestamp": "2026-10-02T19:28:30.114Z",
      "request": {
        "method": "PUT",
        "url": "http://localhost:3001/customers/CUS-3d786679/details",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "email": "jordan@example.com",
          "phone": "555-0100",
          "street": "100 Main Street",
          "city": "Cincinnati",
          "state": "OH",
          "postalCode": "45202"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "emailVerificationId": "EMV-5a8212b3",
        "phoneVerificationId": "PHV-78de6f04"
      }
    },
    "outputs": {
      "emailVerificationId": "EMV-5a8212b3",
      "phoneVerificationId": "PHV-78de6f04"
    },
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-006",
      "affordance": "verifyCustomerPhone",
      "timestamp": "2026-10-02T19:28:30.120Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/customers/CUS-3d786679/phone/verification",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "phoneVerificationId": "PHV-78de6f04"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "verifiedPhone": "555-0100"
      }
    },
    "outputs": {
      "verifiedPhone": "555-0100"
    },
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-007",
      "affordance": "verifyCustomerEmail",
      "timestamp": "2026-10-02T19:28:30.126Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/customers/CUS-3d786679/email/verification",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "emailVerificationId": "EMV-5a8212b3"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "verifiedEmail": "jordan@example.com"
      }
    },
    "outputs": {
      "verifiedEmail": "jordan@example.com"
    },
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-008",
      "affordance": "onboardCustomer",
      "timestamp": "2026-10-02T19:28:30.134Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/customers/CUS-3d786679/onboarding",
        "headers": {},
        "body": null
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Fri, 02 Oct 2026 19:28:30 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "accountId": "ACC-f8887c4e"
      }
    },
    "outputs": {
      "accountId": "ACC-f8887c4e"
    },
    "result": "SUCCESS"
  }
]

=== mamund/grail-public/grail-demo-15-http-bindings-location-bc/config/observations.json
[
  {
    "invocation": {
      "id": "inv-001",
      "affordance": "setCustomerContactDetails",
      "timestamp": "2026-09-23T18:08:42.394Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/execute",
        "headers": {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        "body": {
          "email": "jordan@example.com",
          "phoneNumber": "+1-555-555-0100",
          "streetAddress": "123 Main St.",
          "locality": "Periax",
          "region": "en",
          "postalCode": "12345",
          "country": "US"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Wed, 23 Sep 2026 18:08:42 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "status": "SUCCESS"
      }
    },
    "outputs": {},
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-002",
      "affordance": "testHttpBinding",
      "timestamp": "2026-09-23T18:08:42.400Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/binding-test/customer-123?lang=en",
        "headers": {
          "X-Test-Token": "2026-07",
          "Content-Type": "application/json"
        },
        "body": {
          "emailAddress": "jordan@example.com"
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Wed, 23 Sep 2026 18:08:42 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "status": "SUCCESS",
        "received": {
          "customerId": "customer-123",
          "language": "en",
          "token": "2026-07",
          "emailAddress": "jordan@example.com"
        }
      }
    },
    "outputs": {},
    "result": "SUCCESS"
  },
  {
    "invocation": {
      "id": "inv-003",
      "affordance": "onboardCustomer",
      "timestamp": "2026-09-23T18:08:42.637Z",
      "request": {
        "method": "POST",
        "url": "http://localhost:3001/execute",
        "headers": {},
        "body": null
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "date": "Wed, 23 Sep 2026 18:08:42 GMT",
        "keep-alive": "timeout=5",
        "transfer-encoding": "chunked"
      },
      "body": {
        "status": "SUCCESS"
      }
    },
    "outputs": {},
    "result": "SUCCESS"
  }
]
